bee/urls.py
from django.conf.urls import patterns, url
from bee import views

urlpatterns = patterns('',
    url(r'^$', views.index,name='index'),
    url(r'^company/$',views.company, name='company'), 
    url(r'^company/(?P<company_id>\d+)/$',views.company_info, name='company_info'), 
    url(r'^position/$',views.position , name='position'), 
    url(r'^position/(?P<position_id>\d+)/$',views.position_info, name='position_info'),
)

raccoon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.shortcuts import render_to_response
from raccoon.views import login_view, signin_view , logout_view
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'raccoon.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('console.urls',namespace='console')),
    url(r'^', include('bee.urls',namespace='bee')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login_view.LoginView.as_view() , name='login'),
    url(r'^logout/$', logout_view.logout_view, name='logout'),
    url(r'^join/$', signin_view.SigninView.as_view() , name='join'),
) + staticfiles_urlpatterns()


print urlpatterns

raccoon/views/login_view.py
#coding=utf-8
'''
Created on 2014年6月25日

@author: carvee
'''

from django.http import  HttpResponseRedirect
from django.shortcuts import  render_to_response
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.views.generic import View

class LoginView(View):
    '''
    classdocs
    '''
    def get(self,request, *args,**kwargs):

        next = request.GET.get('next')
        print next
        return render_to_response('site/login.html',context_instance=RequestContext(request))
    
    def post(self,request,*args,**kwargs):
        next = request.GET.get('next')
        print next
        user = authenticate(username=request.POST.get('key_username'),password=request.POST.get('key_pwd'))
        if user is not None :
            if user.is_active :
                login(request,user)
                if not request.POST.get('fixme',None):
                    request.session.set_expiry(0)
                return HttpResponseRedirect(reverse('bee:index'));
        else :
            return render_to_response('site/login.html',{'error':True,'msg':'用户名密码错误,请重试!'});
        

templates/site/company.html
{% extends "base_page.html" %}
{% load staticfiles %}
{% block company%}active{% endblock %}
{% block title%} 找公司 {% endblock %}
{% block sidebar%}
	<div class="eleven wide column">
		<div class="hc_tag">
			<div class="hc_base">
				<div class="ui divided horizontal list">
				  <div class="item"><i class="map marker icon"></i><a>北京</a></div>
				  <div class="item"><i class="map marker icon"></i><a>上海</a></div>
				  <div class="item"><i class="map marker icon"></i><a>深圳</a></div>
				  <div class="item"><i class="map marker icon"></i><a>杭州</a></div>
				</div>
			</div>
			<div class="hc_fields">
			
			<table>
				<tr>
					<td><div class="hc_field_header">发展阶段:</div></td>
					<td>
						<div class="hc_field_content">
						<div class="ui horizontal list">
						  <div class="item active">初创型</div>
						  <div class="item">成长型</div>
						  <div class="item">成熟型</div>
						  <div class="item">已上市</div>
						</div>
					</div>
					</td>
				</tr>
				<tr>
					<td><div class="hc_field_header">行业领域:</div></td>
					<td>
						<div class="hc_field_content">
						<div class="ui horizontal list">
						  <div class="item active">移动互联网</div>
						  <div class="item">电子商务</div>
						  <div class="item">社交</div>
						  <div class="item">企业服务</div>
						  <div class="item">O2O</div>
						  <div class="item">教育</div>
						  <div class="item">文化艺术</div>
						  <div class="item">电子商务</div>
						  <div class="item">社交</div>
						  <div class="item">企业服务</div>
						  <div class="item">O2O</div>
						  <div class="item">教育</div>
						  <div class="item">文化艺术</div>
						</div>
					</div>
					</td>
				
				</tr>
			</table>
			
			</div>
		</div>
		
		<div class="companys">
			<div class="ui three items">
			<div class="item">
				<h2>高大上,欢迎你</h2>
				<a class="image" href="{% url 'bee:company_info' 3 %}" >
				
					<img src="{% static 'images/logo_default.png'%}"> 
					<div class="image-overlay">
							<div>企业erp,HR sources</div>
							<div>北京,成长型</div>
					</div>
				</a>
				<div class="content">
					<a>产品经理</a>
					<a>java工程师</a>
					<div class="ui divider"></div>
					<div class="ctags">
						<span>732</span> <span>美好加油</span> <span>美女多多</span> <span>福利好好</span>
					</div>
				</div>
			</div>
			<div class="item">
				<h2>高大上,欢迎你</h2>
				<a class="image" href="{% url 'bee:company_info' 3 %}">
				
					<img src="{% static 'images/logo_default.png'%}"> 
					<div class="image-overlay">
							<div>企业erp,HR sources</div>
							<div>北京,成长型</div>
					</div>
				</a>
				<div class="content">
					<a>产品经理</a>
					<a>java工程师</a>
					<div class="ui divider"></div>
					<div class="ctags">
						<span>732</span> <span>美好加油</span> <span>美女多多</span> <span>福利好好</span>
					</div>
				</div>
			</div>
			<div class="item">
				<h2>高大上,欢迎你</h2>
				<div class="image">
				
					<img src="{% static 'images/logo_default.png'%}"> 
					<div class="image-overlay">
							<div>企业erp,HR sources</div>
							<div>北京,成长型</div>
					</div>
				</div>
				<div class="content">
					<a>产品经理</a>
					<a>java工程师</a>
					<div class="ui divider"></div>
					<div class="ctags">
						<span>732</span> <span>美好加油</span> <span>美女多多</span> <span>福利好好</span>
					</div>
				</div>
			</div>
			<div class="item">
				<h2>高大上,欢迎你</h2>
				<div class="image">
				
					<img src="{% static 'images/logo_default.png'%}"> 
					<div class="image-overlay">
							<div>企业erp,HR sources</div>
							<div>北京,成长型</div>
					</div>
				</div>
				<div class="content">
					<a>产品经理</a>
					<a>java工程师</a>
					<div class="ui divider"></div>
					<div class="ctags">
						<span>732</span> <span>美好加油</span> <span>美女多多</span> <span>福利好好</span>
					</div>
				</div>
			</div>
			<div class="item">
				<h2>高大上,欢迎你</h2>
				<div class="image">
				
					<img src="{% static 'images/logo_default.png'%}"> 
					<div class="image-overlay">
							<div>企业erp,HR sources</div>
							<div>北京,成长型</div>
					</div>
				</div>
				<div class="content">
					<a>产品经理</a>
					<a>java工程师</a>
					<div class="ui divider"></div>
					<div class="ctags">
						<span>732</span> <span>美好加油</span> <span>美女多多</span> <span>福利好好</span>
					</div>
				</div>
			</div>
			<div class="item">
				<h2>高大上,欢迎你</h2>
				<div class="image">
				
					<img src="{% static 'images/logo_default.png'%}"> 
					<div class="image-overlay">
							<div>企业erp,HR sources</div>
							<div>北京,成长型</div>
					</div>
				</div>
				<div class="content">
					<a>产品经理</a>
					<a>java工程师</a>
					<div class="ui divider"></div>
					<div class="ctags">
						<span>732</span> <span>美好加油</span> <span>美女多多</span> <span>福利好好</span>
					</div>
				</div>
			</div>
			<div class="item">
				<h2>高大上,欢迎你</h2>
				<div class="image">
				
					<img src="{% static 'images/logo_default.png'%}"> 
					<div class="image-overlay">
							<div>企业erp,HR sources</div>
							<div>北京,成长型</div>
					</div>
				</div>
				<div class="content">
					<a>产品经理</a>
					<a>java工程师</a>
					<div class="ui divider"></div>
					<div class="ctags">
						<span>732</span> <span>美好加油</span> <span>美女多多</span> <span>福利好好</span>
					</div>
				</div>
			</div>

		</div>
		</div>
		
	</div>
{% endblock %}

{% block content%}
<div class="five wide column">
	<div class="sidebar">
		<div class="ui one items">
			<div class="item">
				<div class="image">
					<img src="{% static 'images/logo_default.png'%}"> 
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/subject280.jpg'%}"> 
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/subject280.jpg'%}"> 
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/subject280.jpg'%}"> 
				</div>
			</div>
		</div>	
	</div>
</div>
{% endblock %}

templates/site/company_info.html
{% extends "site/company.html" %}
{% load staticfiles %}
{% block sidebar%}
		<div class="eleven wide column">
			
			<div class="c_header">
				<div class="ui grid">
					<div class="c_logo four	 wide column">
						<img class="ui image" src="{% static 'images/logo_default.png'%}">
					
					</div>
					<div class="twelve wide column">
					<div class="c_intro">
						<div class="ui header">
						   途灵岛
						  <div class="sub header">途灵岛(北京)信息技术股份有限公司</div>
						</div>
						<div class="description">
							途灵岛是领先的旅游行业创新运营解决方案提供商
						</div>
						<div class="ui divider"></div>
						<div class="ctags">
						<span>732</span> <span>美好加油</span> <span>美女多多</span> <span>福利好好</span>
					</div>
					</div>	
					</div>
				</div>
			</div>
			
			<div class="ui horizontal icon divider">
				  <i class="circular heart icon"></i>
				</div>
			
			<div class="c_info">
				<div>
					<div class="ui red ribbon label">公司介绍</div>
					<div>
					<p>关于途灵岛 </p>

<p>途灵岛是领先的旅游行业创新运营解决方案提供商。我们为客户提供： </p>

<p>创新的云信息技术解决方案：依托云计算技术，以最具竞争力的成本为客户提供世界领先的信息技术解决方案帮助客户迅速开源节流。 </p>

<p>创新的产业金融解决方案：基于产融结合理念，以深度结合产业特征的金融产品帮助客户提升资产回报，降低运营风险。 </p>

<p>创新的商业模式解决方案：利用顶级咨询顾问全球视野，提供前沿性的商业运营理念助力客户实现可持续性的快速成长。 </p>

<p>企业文化 </p>

<p>创新：在深入理解客户需求的基础上，创新商业模式、业务流程上、服务手段；在服务好会员的同时，做到引领行业的升级。 </p>

<p>执着：追求最佳的用户体验，做最安全、稳定的平台系统；坚持不懈地创造客户价值，助力整个产业升级。 </p>

<p>伙伴关系：我们积极创造专业而友好的组织环境，以团队为导向，保持高度的合作性，彼此分享知识与经验，互相鼓励，互为支持；同时，我们真诚地对待彼此、关心彼此，让每一个人都能 享受在途灵岛的工作与生活。</p>
					</div>
				</div>
				
				<div class="c_prod">
				
					<div class="ui red ribbon label">公司产品</div>
					<div class="cycle-slideshow slideshow_wrap" data-cycle-timeout=8000 data-cycle-fx="fadeout" data-cycle-slides="> a" data-cycle-speed=1500>
						<a><img src="{% static 'images/slider/1.jpg' %}"> </a>
						<a><img src="{% static 'images/slider/2.jpg' %}"> </a>
						<a><img src="{% static 'images/slider/3.jpg' %}"></a>
					</div>
				</div>	
					
				<div class="c_positons">
					<div class="ui red ribbon label">招聘职位</div>
					<ul>
						<li data-url="{% url 'bee:position_info' 3 %}">
						<div class="pub_date">9小时前</div>
							<div class="header">
								java工程师
								<span class="meta">
								[北京]
								</span>
							</div>
							
							<div class="description">
								全职 / 8k-15k / 1-3年 / 本科及以上
							</div>
						</li>
						<li>
						<div class="pub_date">9小时前</div>
							<div class="header">
								java工程师
								<span class="meta">
								[北京]
								</span>
							</div>
							<div class="description">
								全职 / 8k-15k / 1-3年 / 本科及以上
							</div>
						</li>
						<li>
							<div class="pub_date">9小时前</div>
							<div class="header">
								java工程师
								<span class="meta">
								[北京]
								</span>
							</div>
							<div class="description">
								全职 / 8k-15k / 1-3年 / 本科及以上
							</div>
						</li>
						<li>
						<div class="pub_date">9小时前</div>
							<div class="header">
								java工程师
								<span class="meta">
								[北京]
								</span>
							</div>
							<div class="description">
								全职 / 8k-15k / 1-3年 / 本科及以上
							</div>
						</li>
					</ul>
				</div>
			</div>
			
			
		</div>
 {% endblock %}

 {% block cscript %}
	<script type="text/javascript" src="{% static 'js/jquery.cycle2.min.js' %}"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$('.c_positons ul li[data-url]').click(function(){
				window.location = $(this).attr('data-url');
			});
			
		});
	</script>
{% endblock %} 
 

templates/site/home.html
{% extends "base_page.html" %}
{% load staticfiles %}
{% block home%}active{% endblock %}
{% block title %}首页{% endblock %}
{% block content %}

<div class="main thirteen wide right column">

<!-- 轮播 -->

<div class="cycle-slideshow slideshow_wrap" data-cycle-timeout=8000 data-cycle-fx="fadeout" data-cycle-slides="> a" data-cycle-speed=1500>
<a><img src="{% static 'images/slider/1.jpg' %}"> </a>
<a><img src="{% static 'images/slider/2.jpg' %}"> </a>
<a><img src="{% static 'images/slider/3.jpg' %}"></a>
	
	
</div>

<!-- items -->

<div class="ui top attached fluid tabular menu">
  <a class="active item" data-target="com_list">
    找公司
  </a>
  <a class="item" data-target="pos_list">
    找职位
  </a>
</div>
<div id="home-content" class="ui bottom attached segment">

		<div id="pos_list" class="ui selection list hide">
			<div class="ui very relaxed divided list">
				<div class="item">
					<div class="content">
						<a class="header">服务器开发工程师</a> 
						<div class="location">[beijing]</div>
						<div class="description">全职 / 8k-15k / 1-3年 / 本科及以上</div>
					</div>
					
					<div class="right floated date">09:56发布</div>
				</div>
				<div class="item">
					<div class="content">
						<a class="header">Chicago</a>
						<div class="description">A lovely city</div>
					</div>
				</div>
				<div class="item">
					<div class="content">
						<a class="header">Los Angeles</a>
						<div class="description">A lovely city</div>
					</div>
				</div>
			</div>
		</div>


		<div id="com_list" class="ui four items">
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> 
					<a class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
				<div class="content">
					<div class="name">Cute Dog</div>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="ui masked move up reveal image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>
			<div class="item">
				<div class="image">
					<img src="{% static 'images/dog.jpg'%}"> <a
						class="star ui corner label"> <i class="star icon"></i>
					</a>
				</div>
			</div>

		</div>


	</div>


</div>

{% endblock %}


{% block sidebar%}
	<div id='hsidebar' class="three wide column">
{% if user.is_authenticated %}
	<a class="ui massive primary button">
  <i class="add icon"></i>
  推荐简历
</a>
{% endif%}
{% if not user.is_authenticated %}
	<a class="ui massive primary button login" href="{% url 'login' %}">
  <i class="add icon"></i>
  登录/注册
</a>
{% endif%}
	<div class="ui vertical menu">
		<a class="teal item"> <i class="desktop icon"></i> 开发</a> 
		<a class="teal item"> <i class="help icon"></i> 产品</a>
		<a class="teal item"> <i class="bug icon"></i> 测试</a>
		<a class="teal item"> <i class="coffee icon"></i> 管理</a>
		<a class="teal item"> <i class="browser icon"></i> 运维</a>l
		<a class="teal item"> <i class="globe icon"></i> 市场</a>
		<a class="teal item"> <i class="users icon"></i> 高管</a>
	</div>
</div>
{% endblock %}

{% block cscript %}
	<script type="text/javascript" src="{% static 'js/jquery.cycle2.min.js' %}"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			 $('.tabular.menu .item').click(function(){
				 $('#home-content').children('div').hide();
				 var target = $(this).attr('data-target');
				 $('#'+target).show();
			 });
		}
			
		);
	</script>

{% endblock %} 

templates/site/join.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% include 'base_head.html' %}
<title>登录</title>
</head>
<body>
	{% load staticfiles %}
	<div class="ui middle aligned page grid join">
		<div class="container">
			<div class="center aligned column">
				<a href="/"> <img class="ui medium image"
					src="{% static 'images/logo.png' %}">
				</a>
			</div>
			<div class="row">
				<div class="column">
					<form action="{% url 'join'%}" method="post">
						<div class="ui form join">
							<div class="ui error message"></div>
							<div class="two fields">
								<div class="field">
									<label>中文名字</label> <input placeholder="中文名字" name="cn_name"
										type="text">
								</div>
								<div class="field">
									<label>英文名字</label> <input placeholder="英文名字" name=”en_name“
										type="text">
								</div>
							</div>
							<div class="field">
								<label>性别</label>
								<div class="ui fluid selection dropdown">
									<div class="text">选择</div>
									<i class="dropdown icon"></i> <input type="hidden"
										name="gender">
									<div class="menu">
										<div class="item" data-value="male">男</div>
										<div class="item" data-value="female">女</div>
									</div>
								</div>
							</div>
							<div class="field">
								<label>Password</label> <input type="password" name="password"
									placeholder="密码">
							</div>
							<div class="field">
								<label>email</label> <input placeholder="email" name="email"
									type="text">
							</div>
							<div class="field">
								<label>手机号</label> <input type="text" name="mphone">
							</div>
							
							<div class="inline field">
								<div class="ui checkbox">
									<input type="checkbox" name="agree"> <label>同意平台用户协议</label>
								</div>
							</div>
							<div class="ui blue submit button">注册</div>
						</div>


					</form>
				</div>
			</div>


		</div>
	</div>
	{% include 'base_footer.html' %}
	<script type="text/javascript">
		$(document).ready(function() {
			$('.ui.form.join').form({
				cn_name : {
					identifier : 'cn_name',
					rules : [ {
						type : 'empty',
						prompt : '请使用真实姓名,平台实行实名制'
					} ]
				},
				password : {
					identifier : 'password',
					rules : [ 
					            {
									type : 'empty',
									prompt : '请输入密码'
								},
								{
						          type   : 'length[6]',
						          prompt : '请输入至少6位密码'
						        } 
							]
				},
				gender : {
					identifier : 'gender',
					rules : [ {
						type : 'empty',
						prompt : '女同志有特殊福利哦！',
					} ]
				},
				email : {
					identifier : 'email',
					rules : [ {
						type : 'email',
						prompt : '需要您的邮箱,保证帐号安全滴',
					} ]
				},
				mphone : {
					identifier : 'mphone',
					rules : [ {
						type   : 'length[11]',
						prompt : '留下个手机号吧,好方便服务您',
					} ]
				},
				agree : {
					identifier : 'agree',
					rules : [ {
						type : 'checked',
						prompt:'请勾选用户协议',
					} ]
				},
			}, {
				'onSuccess' : function() {
					$('form').submit();
				}
			});

		});
	</script>
</body>
</html>

templates/site/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% include 'base_head.html' %}
<title>登录</title>
</head>
<body style="overflow-y:hidden">
	{% load staticfiles %}
	<div class="ui middle aligned page grid login">
		<div class="container">
			<div class="center aligned column">
				<a href="/"> <img class="ui medium image"
					src="{% static 'images/logo.png' %}">
				</a>
			</div>
			<div class="row">
				<div class="column">
				<form action="{% url 'login'%}" method="post">
					<div class="ui form segment login {% if error%} error {% endif%}">
						<div class="ui error message">
							{% if error %} 
								<ul class="list">
									<li>{{ msg }}</li>
								</ul>
							{% endif%}
						</div>
                    <input type="hidden" name="next" value="{{ next }}">
						<div class="field">
							<label>用户名</label>
							<div class="ui left labeled icon input">
								<input type="text" placeholder="用户名/手机号/邮箱" name="key_username">
								<i class="user icon"></i>
								<div class="ui corner label">
									<i class="asterisk icon"></i>
								</div>
							</div>
						</div>
						<div class="field">
							<label>密码</label>
							<div class="ui left labeled icon input">
								<input type="password" placeholder="密码" name="key_pwd">
								<i class="lock icon"></i>
								<div class="ui corner label">
									<i class="asterisk icon"></i>
								</div>
							</div>
						</div>
						<div class="inline field">
								<div class="ui checkbox">
									<input type="checkbox" name="fixme"> <label>2周免登录</label>
								</div>
							</div>
						<div  class="ui blue fluid submit button" >登录</div>
						<div class="ui horizontal divider">还不是我们的用户?</div>

						<a class="huge green ui labeled fluid button" href="{% url 'join'%}">
							<i class="signup icon"></i> 注册
						</a>
					</div>
</form>
				</div>
			</div>
			

		</div>
	</div>
	{% include 'base_footer.html' %}
	<script type="text/javascript">
		$(document).ready(function() {
			$('.ui.form.login').form({
				key_username : {
					identifier : 'key_username',
					rules : [ {
						type : 'empty',
						prompt : '请使用用户名/手机号/邮箱登录'
					} ]
				},
				key_pwd : {
					identifier : 'key_pwd',
					rules : [ {
						type : 'empty',
						prompt : '请输入密码'
					} ]
				},
			}, {
				'onSuccess' : function() {
					$('form').submit();
				}
			});

		});
	</script>
</body>
</html>

templates/site/position.html
{% extends "base_page.html" %}
{% block position%}active{% endblock %}

templates/site/position_info.html
{% extends "base_page.html" %}
{% load staticfiles %}
{% block position%}active{% endblock %}
{% block title%} 找职位 {% endblock %}
{% block sidebar%}
<div class="eleven wide column">
	
	<div class="p_content">
		<div class="p_header">
			<div class="toplabel">
				<h2 class="header">
					java工程师
				</h2>
				<div class="subdesc">
					图另网招聘
				</div>
			</div>	
			<div class="p_desc">
				<span>6k-12k</span><span>北京</span><span>经验1-3年</span><span>学历不限</span><span>全职</span>
				<p>职位诱惑:拥有广阔的发展空间,有竞争力的薪资</p>
				<div>
					发布时间: 1天前发布
				</div>
			</div>
		</div>
		<div class="ui divider"></div>
		<div class="p_detail">
			<div class="header">职位描述</div>
			<div class="detail">
				<p>岗位职责：</p>
<p>1、负责完成互联网产品的原型、流程和交互界面设计、产品需求文档撰写，</p>
<p>2、协助开发团队理解和掌握需求，对产品需求方向和易用性负责，</p>
<p>3、支持运营团队进行数据收集分析、用户调研与反馈等，持续优化产品。</p>

<p>岗位要求：
<p>1、大学本科以上学历，2年以上互联网产品策划经验者优先；</p>
<p>2、能够独立完成网站产品的原型、产品流程和交互界面的设计；</p>
<p>3、熟练使用office、axure、visio、mindmanager等相关软件；</p>
<p>4、出色的文档撰写能力，优秀的口头表达能力；</p>
<p>5、具备良好的沟通能力和良好的团队合作意识。</p>
			</div>
			<div class="action">
			<a class="ui massive primary button">
  <i class="add icon"></i>
  推 荐 简 历
</a>
		</div>
		</div>
		
	</div>
</div>

{% endblock %}