bee/urls.py
from django.conf.urls import patterns, url
from bee import views

urlpatterns = patterns('',
    url(r'^$', views.index,name='index'),
    url(r'^company/$',views.company, name='company'), 
    url(r'^company/(?P<company_id>\d+)/$',views.company_info, name='company_info'), 
    url(r'^position/$',views.position , name='position'), 
    url(r'^position/(?P<position_id>\d+)/$',views.position_info, name='position_info'),
)

console/urls.py
#coding=utf-8
from django.conf.urls import patterns, url
from console.views import dashboard,explore,resume,project

#dashboard
urlpatterns = patterns('',

    url(r'^console/dashboard/$',dashboard.dashboard,name='dashboard'),
    url(r'^console/dashboard/feeds/$',dashboard.feeds,name='ds_feeds'),
    url(r'^console/dashboard/tasks/$',dashboard.tasks,name='ds_tasks'),
    url(r'^console/dashboard/contributes/$',dashboard.contributes,name='ds_contributes'),
)

#发现
urlpatterns += patterns('',

    url(r'^console/explore$',explore.explore,name='explore'),
    url(r'^console/explore/position$',explore.position,name='position'),
    url(r'^console/explore/tasks/detail$',explore.taskDetail,name='taskDetail'),
)

# 简历管理
urlpatterns += patterns('',
    url(r'^console/resumes$',resume.main,name='resumes'),
    url(r'^console/resume/(\w+)$',resume.resume_detail,name='resume_detail'),
)

# 项目管理
urlpatterns += patterns('',
    url(r'^console/projects$',project.main,name='projects'),
    url(r'^console/project/(\w+)$',project.project_positions,name='projects'),
# 模版

    url(r'^tpl/project/position$',project.tpl_position_slide,name='projects'),
)


# 首页
urlpatterns += patterns('',
    url(r'^console/$',dashboard.main,name='console'),
    url(r'^dashboard/$',dashboard.main),
    url(r'^explore/$',dashboard.main),
    url(r'^resumes/$',dashboard.main),
    url(r'^resume/(\w+)$',dashboard.main),
    url(r'^projects$',dashboard.main),
    url(r'^project/(\w+)$',dashboard.main),
)

raccoon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.shortcuts import render_to_response
from raccoon.views import login_view, signin_view , logout_view
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'raccoon.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('console.urls',namespace='console')),
    url(r'^', include('bee.urls',namespace='bee')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login_view.LoginView.as_view() , name='login'),
    url(r'^logout/$', logout_view.logout_view, name='logout'),
    url(r'^join/$', signin_view.SigninView.as_view() , name='join'),
) + staticfiles_urlpatterns()


print urlpatterns

templates/base_footer.html
{% block script %}{% endblock %}
{% block footer %}{% endblock %}
{% block copyright %}{% endblock %}
{% load staticfiles %} 
<script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'semantic/javascript/semantic.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bee.js' %}"></script>

templates/base_head.html
{% load staticfiles %}  

<link href="{% static 'semantic/css/semantic.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

templates/base_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
{% include 'base_head.html' %}
<title>{% block title%}{% endblock %}</title>
</head>
<body id='home'>
<!-- page header start -->
	<div class="ui page grid masthead segment">
		<div class="row">
			<div class="three wide column">
				<img class="logo" src="{% static 'images/logo.png' %}">
			</div>
			<div class="thirteen wide column">
				<div class=" secondary pointing ui menu">
					<a class="item {% block home%}{% endblock %}" href="{% url 'bee:index'%}"> 首页 </a>
					<a class="item {% block company%}{% endblock %}" href="{% url 'bee:company'%}" > 公司 </a> 
					<a class="item {% block position%}{% endblock %}" href="{% url 'bee:position'%}"> 职位 </a>
					<a class="item {% block resume%}{% endblock %}"> 简历管理 </a> 
					{% if user.is_authenticated %}
					<div class="right item">
						<div class="ui top right inline dropdown ">
						 {{ user.username }}
			            <i class="dropdown icon"></i>
			            <div class="menu">
			              <a href="{% url 'console:console' %}" class="item">工作台</a>
			              <a class="item">个人中心</a>
			              <a href="{% url 'logout' %}" class="item">退出登录</a>
			            </div>
			         </div>
					</div>
					
				<!--  
					<div class="ui top right pointing dropdown link item">
						 <div class="text">{{ user.username }}</div>
			            <i class="dropdown icon"></i>
			            <div class="menu">
			              <a class="item">工作台</a>
			              <a class="item">个人中心</a>
			              <a class="item">退出登录</a>
			            </div>
			         </div>
			        -->
			         {% endif %}
				</div>
			</div>
		</div>

	</div>
	{% block main-couj%}{% endblock %}
<!-- page header end -->

<!-- content start -->
<div class="ui page grid segment">
<div class="row">
	{% block sidebar%}{% endblock %}
	{% block content%}{% endblock %}
</div>

</div>

<!-- content end -->
{% include 'base_footer.html'%}
{% block cscript %}{% endblock %}
</body>
</html>

templates/base_sidebar.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

</body>
</html>

templates/test.html
<!DOCTYPE html>
<html  ng-app="M">
<head>
    <meta charset="UTF-8">
    <title>Insert title here</title>
    {% load staticfiles %}
    {#    <link href='http://fonts.googleapis.com/css?family=Dancing+Script|Audiowide|Playball' rel='stylesheet' type='text/css'>#}
    <link href="{% static 'semantic/css/semantic.css' %}" rel="stylesheet">
    <link href="{% static 'console/style.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'semantic/javascript/semantic.js' %}"></script>
    <script type="text/javascript" src="{% static 'console/js/angular/angular.js' %}"></script>
    <script type="text/javascript" src="{% static 'console/js/angular-route/angular-route.js' %}"></script>

    <script>
        angular('M',['ngRoute'])
                .config()

    </script>

</head>
<body>

    <div ng-controller="MainCtrl as main">
        Choose:
        <a href="Book/Moby">Moby</a> |
         <a href="Book/Gateby">Gateby</a> |
         <a href="Book/Scarlet">Scarlet</a> |

        <ng-view></ng-view>

    </div>

</body>
</html>